# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sat, 29 Oct 2022 17:12:24 +0000
*	@ALL	8
catalogos	@ALL	1
centro	@ALL	1
documentos	@ALL	1
faqs	@ALL	1
integradores	@ALL	1
playground:*	@ALL	0
soporte	@ALL	1
start	@ALL	1
start	@user	2
wiki:dokuwiki	@ALL	0
wiki:syntax	@ALL	0
wiki:welcome	@ALL	0
inicio	@ALL	1
catalogos	@audi	1
centro	@audi	0
datwyler	@audi	0
documentos	@audi	0
faqs	@audi	0
inicio	@audi	0
integradores	@audi	0
soporte	@audi	0
start	@audi	1
datwyler-audi	@ALL	0
datwyler-audi	@user	0
datwyler-audi	@audi	1
