<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: apolanco
 * Date: Mon, 31 Oct 2022 20:45:43 +0000
 */

$conf['title'] = 'marathongroup-wiki';
$conf['start'] = 'Inicio';
$conf['lang'] = 'es';
$conf['license'] = '';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
